### ISSUE TITLE
Prompts are annoying; currency should be differently selectable

### ISSUE THREAD

**Issue by tekknolagi** [filfreire/Moneeee#4]

**Comment by filfreire** [comment]
@tekknolagi indeed.
For currency what do you have in mind? Something like a dropdown?

**Comment by tekknolagi** [comment]
Somebody suggested clicking on the currency symbol to have it cycle through. Perhaps that's something that could be in localStorage?

**Comment by filfreire** [comment]
@tekknolagi yes, it shouldn't be to hard to implement, I'll try it out later today.

**Comment by filfreire** [comment]
@tekknolagi prompts have been removed!
Check out https://filfreire.com/Moneeee/
